### PR TITLE
Rebuilt website front end for easier readability and manipulation.

### PR DESCRIPTION
**Pull request by ObiTracks**
Ok Im going to bed now but I was up all night rebuilding the css from scratch after creating a style guide list to organize the different types of elements on the page. Now, @JoseGrangerSalgado I know how you changed the html to make the profile page exist on the dashboard and only become visible on a button click, well now its even easier since all you need to do to that element is change its property from display none to display visible or whatever - the css grid will automatically add it and readjust the other divs. 

There is a file called styleguide.txt to show how the classes are organized, and I deleted the old code since anyone can get it from here on github. Have a look at the guide and the html code to get your bearings and load the items from whatever JSON comes its way. There are certain ids on important elements for easy access through Javascript @JoseGrangerSalgado @jpaints3 @josueetcom

### CODE REVIEW

**Comment by ObiTracks** [comment]
One more thing, the htmlComponents.html page is for your reference to see how to structure elements like cards and menu items (aka strips).

**Comment by ObiTracks** [comment]
I also haven't copied the code into matchdashboard.html because now I think we can make this a one page website like what @JoseGrangerSalgado was thinking by adding the personal profile page to the dashboard. @jpaints3 @josueetcom .

**Review by josueetcom — APPROVED** [review]
Approving to get you unblocked. Though FYI, these kinds of changes can be disruptive for others if they've already started making changes based on the previous layout.

**Comment by ObiTracks** [comment]
> Approving to get you unblocked. Though FYI, these kinds of changes can be disruptive for others if they've already started making changes based on the previous layout.

After looking at the website code I'd done before, I realized that going ahead with it would cause more problems than any adjustments to changes made by anybody else like Jose altering it. Its simpler and more readable for it, with only minor changes to any javascript code needed. Basically my old code even hurt my eyes since it was even hard for me to follow - I built it in like a couple days without creating a logical guide

**Review by jpaints3 — APPROVED** [review]
I would add the option to update a teachlist somewhere in the code but other than that it looks great!

**Pull request merged**
