### PR TITLE
Login

### PR DESCRIPTION
**Pull request by JoseGrangerSalgado**
Login done, will leave all the changes to dashboard.html to another pull request.

### CODE REVIEW

**Review by ObiTracks — COMMENTED** [review]
Approving in the name of quick time progress, don't have time to look properly rn but I trust u

**Review by ObiTracks — APPROVED** [review]
Approving in the name of quick time progress, don't have time to look properly rn but I trust u

**Review by jpaints3 — APPROVED** [review]
Where is the profile creation survey now?

**Comment by JoseGrangerSalgado** [comment]
> Where is the profile creation survey now?

What profile creation survey?

**Pull request merged**
